### ISSUE TITLE
RV Command line doesn't open even with Lua installed and PATH Variables added 

### ISSUE THREAD

**Issue by RonXD11** [hataori-p/real-voice-basic#1]
I'm not sure if I'm Doing something wrong but I'm pretty sure did everything right (Installed lua binaries, Modified rv.bat to add the correct directory and added the directory in System PATH Variables) but The RV Command line still closes immediately after trying to run it
![image](https://user-images.githubusercontent.com/102899973/161420811-dbe8d183-8249-4eb4-bbcf-6871538e77f7.png)
![image](https://user-images.githubusercontent.com/102899973/161420834-0124d630-7aee-410b-a9ce-839c6051ecaf.png)
![image](https://user-images.githubusercontent.com/102899973/161420854-ea2e7238-7974-4009-99f8-1c2a668c346e.png)

**Comment by hataori-p** [comment]
Please try to download and use 32 bit Lua bunaries and see if it is also crashing.

https://sourceforge.net/projects/luabinaries/files/5.4.2/Tools%20Executables/lua-5.4.2_Win32_bin.zip/download

**Comment by RonXD11** [comment]
> Please try to download and use 32 bit Lua bunaries and see if it is also crashing.
> 
> https://sourceforge.net/projects/luabinaries/files/5.4.2/Tools%20Executables/lua-5.4.2_Win32_bin.zip/download

Hello and thanks for your reply. I Did try using the 32bit binaries as well on 2 computers and it still didn't work so chances are I'm doing something wrong but any help would be really appreciated

**Comment by hataori-p** [comment]
Now I see it - you have created variable RV in system variables, but you need to find variable PATH and append your path to it after semicolon.

**Comment by hataori-p** [comment]
See here
https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/

**Comment by RonXD11** [comment]
> See here https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/

![image](https://user-images.githubusercontent.com/102899973/161423869-e598ed7b-fb17-4374-b9bf-75b7d4795790.png)
is this right?

**Comment by hataori-p** [comment]
It should be a path to rv.bat file - F:\Synth...\Scripts\RealVoice

Then close the command line window and open it again (if you did't).

Then write "set" command and you should see listing of variables, one of which is PATH including your F:\... path.
This is for a chech.

Then run "rv" command if it writes something.

**Comment by RonXD11** [comment]
> It should be a path to rv.bat file - F:\Synth...\Scripts\RealVoice
> 
> Then close the command line window and open it again (if you did't).
> 
> Then write set command and you should see listing of variables, one of which is PATH including you F:... path. This is for a chech.
> 
> Then run rv command if it writes something.

![image](https://user-images.githubusercontent.com/102899973/161424340-94e51c14-07b2-48cf-8880-ae1efced0232.png)

The F:\... path does show up and I changed to to ....\Scripts\RealVoice but it still doesn't open

**Comment by hataori-p** [comment]
It's there at the end in the picture. It's right now.

What does it write if you now run rv (alone)?

**Comment by RonXD11** [comment]
"F:/Synthesizer V Studio Basic/Scripts/RealVoice/lua54.exe: cannot open F:/Synthesizer V Studio Basic/Scripts/RealVoice/scripts/.lua: No such file or directory"




> It's there at the end in the picture. It's right now.
> 
> What it writes if you now run rv (alone)?

**Comment by hataori-p** [comment]
OK - then run

rv filterPitch

**Comment by RonXD11** [comment]
rv filterPitch
RV: Low pass filter of the Praat pitch object (short text file format)
usage: rv filterPitch <input_pitch_file> <filtered_output_pitch_file>

I guess it works now lol

**Comment by hataori-p** [comment]
Yes! Try to cd into some other directory (your project dir eg.) and run it again - it should do the same.
Then run other two scripts

rv notesFromTextGrid
rv notesToTextGrid

**Comment by RonXD11** [comment]
YES! It works now! Thanks for the help!

**Comment by hataori-p** [comment]
Now it is on you & Praat.
Let me know when you do some cover!!

Closing issue.

**Comment by RonXD11** [comment]
Cool. Thanks again
